name: GetPRNr

on:
  push:
    branches:
      main


jobs:
  get_commit:
    name: Get commit SHA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Show commits
        run: |
          git status
          git log -n 5
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: pr nr
        run: |
          msg=${{ github.event.commits[0].message }}
          nr=$(grep -oP '\(#\K[0-9]+' <<< "$msg" | head -n 1)
          echo $nr
