name: GetPRNr

on:
  push:
    branches:
      main


jobs:
  get_commit:
    name: Get commit SHA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Show commits
        run: |
          git status
          git log -n 5
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: pr nr
        run: |
          len="${{ size(github.event.commits) }}"
          echo "Length: $len"
          msg="${{ github.event.commits[0].message }}"
          nr=$(grep -oP '\(#\K[0-9]+' <<< "$msg" | head -n 1)
          if [ -z "$nr" ]
          then
            echo "PR nr not found in $msg"
            echo "pr_found=false" >> $GITHUB_ENV
          else
            echo "PR NR: $nr"
            echo "pr_nr=$nr" >> $GITHUB_ENV
            echo "pr_found=true" >> $GITHUB_ENV
          fi
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        if: env.pr_found == 'true'
        with:
          issue-number: ${{ env.pr_nr }}
          body: |
            This comments comes from GA
